<?php
declare(strict_types=1);

if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-ajax-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <div class="block-content filter-content sidebar-shop sidebar-left">
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="widget">
                    <?= $block->getChildHtml('state') ?>
                    <div class="block-actions filter-actions">
                        <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                    </div>
                </div>
            <?php endif; ?>
            <?php
            $wrapOptions = false;
            $activeKey = 0;
            $activeArray = [];
            ?>
            <div class="block-title filter-title">
                <strong data-role="title"><?= $block->escapeHtml(__('Comprar por')) ?></strong>
            </div>
            <?php foreach ($block->getFilters() as $key => $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                       <div class="filter-options widget widget-filter" id="narrow-by-list" data-role="content">
                    <?php $wrapOptions = true;
                    endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                    <?php
                    if ($this->helper('Rokanthemes\LayeredAjax\Helper\Data')->isOpenAllTab()) {
                        $activeArray[] = $activeKey;
                    }
                    $activeKey++;
                    ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
                <script type="text/x-magento-init">
                    {
                        "#narrow-by-list": {
                            "accordion": {
                                "openedState": "active",
                                "collapsible": true,
                                "active": <?= /* @noEscape */ $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($activeArray) ?>,
                                "multipleCollapsible": true
                            },
                            "Rokanthemes_LayeredAjax/js/layeredajax": {}
                        }
                    }
                </script>
            <?php endif; ?>
        </div>
        <div id="layered_ajax_overlay" class="layered_ajax_overlay" aria-hidden="true" hidden>
            <div><img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>" alt="<?= $block->escapeHtmlAttr(__('Loading')) ?>" width="48" height="48" decoding="async"></div>
        </div>
    </div>
<?php endif; ?>
