<?php

declare(strict_types=1);

namespace GrupoAwamotos\CatalogFix\Plugin\Catalog\ResourceModel\Category;

use Magento\Catalog\Model\ResourceModel\Category\Collection;
use Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator;

/**
 * Evita duplicata de categorias no menu quando há redirect de URL antiga + rewrite canônico
 * (mesmo entity_id, dois is_autogenerated=1 → joinUrlRewrite duplica linhas na coleção).
 */
class CollectionJoinUrlRewritePlugin
{
    public function aroundJoinUrlRewrite(Collection $subject, callable $proceed): Collection
    {
        $subject->joinTable(
            'url_rewrite',
            'entity_id = entity_id',
            ['request_path'],
            sprintf(
                '{{table}}.is_autogenerated = 1'
                . ' AND {{table}}.store_id = %d'
                . ' AND {{table}}.entity_type = \'%s\''
                . ' AND {{table}}.target_path LIKE \'catalog/%%\'',
                $subject->getStoreId(),
                CategoryUrlRewriteGenerator::ENTITY_TYPE
            ),
            'left'
        );

        return $subject;
    }
}
