<?php

declare(strict_types=1);

namespace GrupoAwamotos\B2B\Setup\Patch\Data;

use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\UrlRewrite\Model\UrlRewriteFactory;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite as UrlRewriteData;

class CreateB2BLandingUrlRewrite implements DataPatchInterface
{
    /**
     * @var ModuleDataSetupInterface
     */
    private $moduleDataSetup;

    /**
     * @var UrlRewriteFactory
     */
    private $urlRewriteFactory;

    /**
     * @param ModuleDataSetupInterface $moduleDataSetup
     * @param UrlRewriteFactory $urlRewriteFactory
     */
    public function __construct(
        ModuleDataSetupInterface $moduleDataSetup,
        UrlRewriteFactory $urlRewriteFactory
    ) {
        $this->moduleDataSetup = $moduleDataSetup;
        $this->urlRewriteFactory = $urlRewriteFactory;
    }

    /**
     * @inheritdoc
     */
    public function apply()
    {
        $this->moduleDataSetup->startSetup();

        $urlRewriteModel = $this->urlRewriteFactory->create();

        // Check if exists
        $existing = $urlRewriteModel->getCollection()
            ->addFieldToFilter('request_path', 'seja-revendedor')
            ->addFieldToFilter('store_id', 1)
            ->getFirstItem();

        if (!$existing->getId()) {
            $urlRewriteModel->setStoreId(1)
                ->setIsAutogenerated(0)
                ->setRequestPath('seja-revendedor')
                ->setTargetPath('b2b/marketing/landing')
                ->setRedirectType(0)
                ->save();
        }

        $this->moduleDataSetup->endSetup();
    }

    /**
     * @inheritdoc
     */
    public static function getDependencies()
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    public function getAliases()
    {
        return [];
    }
}
